# Generated by Django 5.1.1 on 2024-09-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew_6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d/')),
            ],
        ),
    ]
